apiVersion: v1
kind: Namespace
metadata:
  name: aura-trading
  labels:
    name: aura-trading
    app: aura
    environment: production
  annotations:
    description: "Namespace for AURA Trading System"
    contact: "devops@aura-trading.com"
    version: "1.0.0"

---
# Resource Quota para controlar uso de recursos
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aura-resource-quota
  namespace: aura-trading
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "10"
    configmaps: "10"

---
# Network Policy para segurança
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aura-network-policy
  namespace: aura-trading
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: aura-trading
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          name: aura-trading
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80