# Configuração para ambiente de desenvolvimento
environment: development

# Configurações do servidor
server:
  port: 8000
  host: localhost
  cors:
    enabled: true
    origins: 
      - http://localhost:3000
      - http://localhost:3001

# Configurações do banco de dados
database:
  host: localhost
  port: 5432
  name: aura_trading
  user: postgres
  password: password
  pool:
    min: 2
    max: 10
    idle_timeout: 30000
  ssl: false

# Configurações do Redis
redis:
  host: localhost
  port: 6379
  database: 0
  password: null
  connection_timeout: 5000
  command_timeout: 5000

# Configurações JWT
jwt:
  secret: your-super-secret-jwt-key-change-this-in-production
  refresh_secret: your-super-secret-refresh-key-change-this-in-production
  expires_in: 1h
  refresh_expires_in: 7d
  algorithm: HS256

# Configurações da Binance
binance:
  use_testnet: true
  base_url: https://api.binance.com
  testnet_url: https://testnet.binance.vision
  websocket_url: wss://stream.binance.com:9443/ws
  testnet_websocket_url: wss://testnet.binance.vision/ws
  rate_limits:
    requests_per_minute: 1200
    orders_per_second: 10
    orders_per_day: 200000

# Configurações de logging
logging:
  level: debug
  format: json
  file: logs/aura-dev.log
  max_size: 100MB
  max_files: 5
  console: true

# Configurações de segurança
security:
  encryption_key: your-32-character-encryption-key-here
  rate_limit:
    window_ms: 900000  # 15 minutos
    max_requests: 100
  session_timeout: 3600000  # 1 hora

# Configurações de email (opcional para desenvolvimento)
email:
  enabled: false
  smtp:
    host: smtp.gmail.com
    port: 587
    secure: false
    auth:
      user: ""
      password: ""
  from: noreply@aura-trading.com
  templates_path: templates/emails

# Configurações de notificações
notifications:
  slack:
    enabled: false
    webhook_url: ""
    channel: "#alerts"
    username: "AURA Bot"
  
  webhook:
    enabled: false
    url: ""
    timeout: 5000

# Configurações de monitoramento
monitoring:
  enabled: true
  metrics:
    enabled: true
    interval: 30000  # 30 segundos
  health_checks:
    enabled: true
    interval: 60000  # 1 minuto
  alerts:
    enabled: false

# Configurações de cache
cache:
  ttl:
    market_data: 5000      # 5 segundos
    user_session: 3600000  # 1 hora
    strategy_state: 300000 # 5 minutos
    portfolio_data: 30000  # 30 segundos

# Configurações de performance
performance:
  max_concurrent_strategies: 100
  max_concurrent_backtests: 5
  market_data_buffer_size: 1000
  order_execution_timeout: 30000  # 30 segundos

# Configurações de desenvolvimento
development:
  hot_reload: true
  debug_mode: true
  mock_binance: false
  seed_data: true
  auto_migrate: true