services:
  mcp-bridge:
    build: .
    container_name: mcp-bridge
    ports:
      - "5000:5000"
    volumes:
      # CRÍTICO: Monta o socket do Docker para gerenciar outros containers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge