name: Cleanup Old Images

on:
  schedule:
    # Executa todo domingo às 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [backend, frontend]

    steps:
    - name: Delete old images
      uses: actions/delete-package-versions@v4
      with:
        package-name: ${{ github.repository }}/${{ matrix.service }}
        package-type: container
        min-versions-to-keep: 10
        delete-only-untagged-versions: false
        ignore-versions: '^(latest|stable|main|develop)$'